apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Replace=true
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/mongodb
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain