apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
  annotations:
    argocd.argoproj.io/sync-wave: "0
type: Opaque
stringData:
  JWT_SECRET: "change-this-in-production"
  NEXTAUTH_SECRET: "change-this-in-production"